version: "3.8"
services:
   frontend:
     restart: always
     image: front:latest
     build: ./front
     volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
     tty: true
     ports:
       - 3000:3000
     environment:
       - CHOKIDAR_USEPOLLING=true
   database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
   backend:
    restart: always
    image: back:latest
    build: ./back
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    tty: true
    environment:
      NODE_ENV: development
    depends_on: 
      - database

volumes:
  mongodb_data_container: